name: Automated Tests

on: [push, pull_request]

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install
      # clone `.env.development` to `.env` for testing
      - run: cp .env.development .env
      - run: bun run services:up
      - run: bun run test
